# dataset params
dataset_path: PATH_TO_DATASET # Replace with actual path or use environment variable
num_classes: 10
image_width: 224
image_height: 224

# Tuning params
epochs: 1000
patience: 30
early_stopping_metric: val/precision

learning_rate: 
  - 0.1
  - 0.01
  - 0.001
  - 0.0001

batch_size: 
  - 8
  - 16
  - 32

optimizer: 
  - adam
  - sgd

scheduler:
  type: 
    - "StepLR"
    - "ExponentialLR"
    - "ReduceLROnPlateau"
  step_size:  # Specific to StepLR
    - 30
    - 50
  gamma:  # Common in several schedulers
    - 0.1
    - 0.01
  patience:  # Specific to ReduceLROnPlateau
    - 10
    - 20
  factor:  # Specific to ReduceLROnPlateau
    - 0.5
    - 0.1